name: Publish
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Configure CI Git User
        run: |
          git config --global user.name '@hirezio'
          git config --global user.email 'hirezio@users.noreply.github.com'

      - name: Publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: yarn semantic-release
